### ISSUE TITLE
In the reasoning process of ICV, is the model aware of the context?

### ISSUE THREAD

**Issue by aohenuo** [roeehendel/icl_task_vectors#3]
Dear Roe,

Thank you for providing the code to your interesting paper. The idea of ICV in your paper is intriguing. However, theoretically, aside from the ICV, any other context is invisible to the model during inference. Could you specify which part of your implementation makes the rest of the context invisible?

**Comment by roeehendel** [comment]
Hi,
Note that in `run_task_vector`, we run `modulated_generate`, corresponding in the paper to the second (yellow) part of the computation denoted by 𝑓. This method includes the `include_train` parameter, defaulting to `False`. This parameter is passed to `tokenize_datasets`, which consequently discards the rest of the context, specifically the demonstrations (which can be thought of as the "train" examples of the dataset, therefore the name of the parameter).
I hope this clarification helps, acknowledging that we could have made this aspect clearer in the code.

**Comment by aohenuo** [comment]
i see it, thank u very much!😘
